### PR TITLE
fix(client): limit the number of connections dependent on the blob size

### LINKED ISSUE #556: Tune client parameters for large blobs
When storing largo blobs (100s of MiB) on the Walrus devnet, there are lots of errors like the following:

> 2024-06-19T15:54:47.598998Z DEBUG reserve_and_store_blob{blob_id="4uaZ2AHAyDlEou7E-17QmM3-OmBxhOvO5rHEWF-ZMvE"}:store_metadata_and_pairs:store_sliver_by_axis: walrus_sdk::client: error=error sending request for url (http://lax-dnt-sto-00.devnet.sui.io:9185/v1/blobs/4uaZ2AHAyDlEou7E-17QmM3-OmBxhOvO5rHEWF-ZMvE/slivers/96/primary)

While the store operation succeeds in the end, this is still not ideal. My suspicion is that when storing many large slivers in parallel (here one primary sliver is 10 MiB) some of those requests fail due to timeouts or something like this.

One possibility would be to adapt the number of parallel connections based on the blob size.

### PR DESCRIPTION
**Pull request by mlegner**
This adds a added a `max_data_in_flight` config parameter with a default of 100 Mb = 12.5 MB and limits the number of connections for storing and reading slivers such that their total amount of data does not exceed that maximum.

It also decreases the default timeout to limit the impact of Byzantine nodes.

Requires some documentation changes. There we can also emphasize that the communication config may not work well for large blobs with very bad networking.

Closes #556

### CODE REVIEW

File: crates/walrus-service/src/client/config.rs [hunk 1]
```diff
@@ -75,9 +69,94 @@ impl ClientCommunicationConfig {
...
+            max_concurrent_sliver_reads,
+            max_concurrent_metadata_reads,
+            max_concurrent_status_reads,
+            max_data_in_flight,
+        }
+    }
+
+    fn max_connections_for_request_and_blob_size(
+        &self,
+        request_size: usize,
```
Comment (giac-mysten) [inline crates/walrus-service/src/client/config.rs]: Suggestion: Use `NonZeroUsize` to avoid division by 0?

File: crates/walrus-service/src/client/config.rs [hunk 2]
```diff
@@ -75,9 +69,94 @@ impl ClientCommunicationConfig {
...
+    }
+
+    fn sliver_size_for_blob(
+        &self,
+        blob_size: NonZeroU64,
+        encoding_config: &EncodingConfig,
+    ) -> usize {
+        encoding_config
+            .sliver_size_for_blob::<Primary>(blob_size.get())
+            .expect("blob should not be too large to be encoded")
```
Comment (giac-mysten) [inline crates/walrus-service/src/client/config.rs]: Question: How do we enforce this? Since `CommunicationLimits` is `pub`, `blob_size` could be anything?

File: crates/walrus-service/src/client/config.rs [hunk 3]
```diff
@@ -75,9 +69,94 @@ impl ClientCommunicationConfig {
...
+            .max(1)
+    }
+
+    fn sliver_size_for_blob(
+        &self,
+        blob_size: NonZeroU64,
+        encoding_config: &EncodingConfig,
+    ) -> usize {
+        encoding_config
+            .sliver_size_for_blob::<Primary>(blob_size.get())
```
Comment (giac-mysten) [inline crates/walrus-service/src/client/config.rs:127]: Question/remark: Seems we are over-approximating (by 33%?) the data in transfer by only using the size of primary slivers, right? I think it's fair.

File: crates/walrus-service/src/client.rs [hunk 4]
```diff
@@ -499,7 +476,14 @@ impl<T> Client<T> {
         let enough_source_symbols =
             |weight| weight >= self.encoding_config.n_source_symbols::<U>().get().into();
         requests
-            .execute_weight(&enough_source_symbols, self.max_concurrent_sliver_reads)
+            .execute_weight(
+                &enough_source_symbols,
+                self.communication_limits
+                    .max_concurrent_writes_for_blob_size(
```
Comment (giac-mysten) [inline crates/walrus-service/src/client.rs]: Question: this is a bit confusing. We are in the `request_slivers_and_decode` function, and are requesting with a `max_concurrent_writes_for_blob_size` limit?
did you mean `reads`?

File: crates/walrus-service/src/client.rs [hunk 5]
```diff
@@ -112,34 +105,19 @@ impl Client<()> {
...
-            config.communication_config.max_concurrent_metadata_reads;
-        let max_concurrent_status_reads = config
-            .communication_config
-            .max_concurrent_status_reads
-            .unwrap_or(default::max_concurrent_status_reads(committee.n_shards()));
-        let global_write_limit = Arc::new(Semaphore::new(max_concurrent_writes));
+        let communication_limits =
+            CommunicationLimits::new(&config.communication_config, encoding_config.n_shards());
+        let global_write_limit =
+            Arc::new(Semaphore::new(communication_limits.max_concurrent_writes));
```
Comment (giac-mysten) [inline crates/walrus-service/src/client.rs:115]: Question: Is the write limit per blob never applied? See line 348, there we don't limit the number of storage nodes, and the semaphore here uses the generic value?

File: crates/walrus-service/src/client/config.rs (hunk 2 above)
Comment (mlegner) [reply crates/walrus-service/src/client/config.rs]: Good point. Let me make the struct (more) private and emphasize that these functions panic if they are not called with valid blob sizes.

File: crates/walrus-service/src/client.rs (hunk 4 above)
Comment (mlegner) [reply crates/walrus-service/src/client.rs]: Yes, this was an oversight.

File: crates/walrus-service/src/client.rs (hunk 5 above)
Comment (mlegner) [reply crates/walrus-service/src/client.rs:115]: Hmm... You are right. But why did the behavior change then...? 🤔 
I will invistigate.

Comment (mlegner) [reply crates/walrus-service/src/client.rs:115]: It seems the change in behavior was just due to different networking conditions, so my "fix" didn't actually change anything. 🤦

I will try to apply a blob-specific connection limit.

File: crates/walrus-service/src/client/config.rs (hunk 3 above)
Comment (mlegner) [reply crates/walrus-service/src/client/config.rs:127]: Yes, that's true. I didn't find a convenient way of making this more precise. But as the default value is anyway somewhat arbitrary, I don't think this discrepancy matters too much.

File: crates/walrus-service/src/client.rs (hunk 5 above)
Comment (mlegner) [reply crates/walrus-service/src/client.rs:115]: OK, I've now fixed the behavior for the store operation by introducing yet another semaphore... 😅 
This seems to work, but makes the setup a bit more complicated. Let me know what you think.
