### PR TITLE
fix(publisher): enforce sequential Sui transactions

### LINKED ISSUE #577: Publisher cannot handle concurrent requests
The publisher currently uses a single `SuiContractClient` for all requests. 
If two clients try to upload a blob simultaneously, the gas or payment object can get locked which makes the request fail.

### PR DESCRIPTION
**Pull request by mlegner**
Verified this locally by sending 100 simultaneous requests. Before this change, this caused many errors like the following:
```
2024-08-14T15:55:42.428142Z ERROR put_blob{epochs=1}: walrus_service::client::daemon::routes: error storing blob error=client internal error: RPC call failed: ErrorObject { code: ServerError(-32002), message: "Failed to sign transaction by a quorum of validators because of locked objects. Retried a conflicting transaction Some(TransactionDigest(PBbxoZKbhRTnUi1UBfMgWGAvuEzmizFwWGAMrKkXsPt)), success: Some(true)", data: Some(RawValue({"PBbxoZKbhRTnUi1UBfMgWGAvuEzmizFwWGAMrKkXsPt":[["0x2ec6a9f00d3492f889902c6fc926524f2b7539cb9975b6a1f67733eb06ca1376",212,"B1SAu9o26hxTwbDcTofnFF9xzjwDpVVykDmQC7UAer5S"],["0x2ec6a9f00d3492f889902c6fc926524f2b7539cb9975b6a1f67733eb06ca1376",212,"B1SAu9o26hxTwbDcTofnFF9xzjwDpVVykDmQC7UAer5S"],["0x2ec6a9f00d3492f889902c6fc926524f2b7539cb9975b6a1f67733eb06ca1376",212,"B1SAu9o26hxTwbDcTofnFF9xzjwDpVVykDmQC7UAer5S"],["0x2ec6a9f00d3492f889902c6fc926524f2b7539cb9975b6a1f67733eb06ca1376",212,"B1SAu9o26hxTwbDcTofnFF9xzjwDpVVykDmQC7UAer5S"]]})) }
```

With the fix, all 100 requests are handled successfully.

Closes #577

### CODE REVIEW

File: crates/walrus-sui/src/client.rs [hunk 1]
```diff
@@ -264,9 +259,10 @@ impl SuiContractClient {
         }
     }
 
-    /// Returns the wallet context used by the client.
-    pub fn wallet(&mut self) -> &mut WalletContext {
-        &mut self.wallet
+    /// Returns the active address of the client.
+    pub fn address(&mut self) -> anyhow::Result<SuiAddress> {
+        let mut wallet = self.wallet.blocking_lock();
+        wallet.active_address()
```
Comment (karlwuest) [inline crates/walrus-sui/src/client.rs]:
```suggestion
    pub fn address(&self) -> anyhow::Result<SuiAddress> {
        self.wallet_address
```
Important: `blocking_lock` on a `tokio::sync::Mutex` will panic if called from an async context, so we shouldn't use this in any function that may be called from a tokio task.
