### PR TITLE
fix(client): avoid reading `Blob` object after certification

### LINKED ISSUE #728: Make blob certification more robust against fullnode load balancing
Similar to #587.

See https://github.com/MystenLabs/walrus-sites/issues/178#issuecomment-2309606160 for context.

### PR DESCRIPTION
**Pull request by mlegner**
The only purpose of this was to check that the `certified_epoch` was updated correctly. However, we *know* that this must have happened if the `certify_blob` contract completed without error. We can therefore simply modify the `Blob` object locally and safe one RPC request.

This speeds up the write process and avoids spurious errors in case of load-balancing between Sui full nodes.

Closes #728

### CODE REVIEW

File: crates/walrus-sui/src/client.rs [hunk 1]
```diff
@@ -164,11 +164,13 @@ pub trait ContractClient: Send + Sync {
 
     /// Certifies the specified blob on Sui, given a certificate that confirms its storage and
     /// returns the certified blob.
+    // NB: This intentionally takes an owned `Blob` object even though it is not required, as the
+    // corresponding object on Sui will be changed in the process.
```
Comment (giac-mysten) [inline crates/walrus-sui/src/client.rs:168]: Nice idea, I like that we are "destroying" the outdated object this way.

File: crates/walrus-service/src/client.rs [hunk 2]
```diff
@@ -272,30 +269,30 @@ impl<T: ContractClient> Client<T> {
...
+        // We do not need to wait explicitly as we anyway retry all requests to storage nodes.
+        let certificate = self
+            .send_blob_data_and_get_certificate(&metadata, &pairs)
+            .await?;
+        self.sui_client
+            .certify_blob(blob.clone(), &certificate)
             .await
             .map_err(|e| ClientError::from(ClientErrorKind::CertificationFailed(e)))?;
 
+        blob.certified_epoch = Some(self.committee.epoch);
```
Comment (giac-mysten) [inline crates/walrus-service/src/client.rs:286]: Remark: with epoch change this may be problematic, for example if the retry is within `send_blob_data_and_get_certificate`. Should keep this in mind.

Comment (mlegner) [reply crates/walrus-service/src/client.rs:286]: Yes, that's a good point...

I'll add a comment about this.
