### PR TITLE
fix(logs): canonicalize log entries and reduce overall verbosity

### LINKED ISSUE #1086: Revisit log levels
We should make sure we have consistent log levels everywhere so that we can globally set log levels as follows:
- INFO: Normal operation. Sufficient output to be able to follow the storage-node or client process and get notified of issues.
- DEBUG: Additional help with low-level issues but not too verbose such that it can be run for ~days.
- TRACE: Any additional messages that would otherwise pollute the `DEBUG` log.

### PR DESCRIPTION
**Pull request by mlegner**
Among others, this includes the following changes:
- reduce verbosity for some log entries, notably for successful requests to the store sliver endpoint
- increase level of some epoch-related log entries to INFO
- consistently print Debug formatting for errors on ERROR level
- use consistent capitalization
- prefer recording metadata as fields as opposed to including them in the log string
- qualify tracing macros with `tracing::` prefix
- simplify syntax for including fields in log entries

Closes #1086

### CODE REVIEW

File: crates/walrus-service/src/client/cli/runner.rs [hunk 1]
```diff
@@ -268,7 +268,7 @@ impl ClientCommandRunner {
         let client = get_contract_client(self.config?, self.wallet, self.gas_budget, &None).await?;
 
         if dry_run {
-            tracing::info!("Performing dry-run store for file {}", file.display());
+            tracing::info!("performing dry-run store for file '{}'", file.display());
```
Comment (giac-mysten) [inline crates/walrus-service/src/client/cli/runner.rs:320]: General question: where do we use string formatting, and where use metadata fields instead? is this because it's just the client startup runner?

File: crates/walrus-service/src/client/refill.rs [hunk 2]
```diff
@@ -113,7 +113,7 @@ impl WalletCoinRefill {
     }
 
     async fn send_gas(&self, address: SuiAddress) -> Result<()> {
-        tracing::debug!("Sending gas to address: {:?}", &address);
+        tracing::debug!("sending gas to {address}");
```
Comment (giac-mysten) [inline crates/walrus-service/src/client/refill.rs]:
```suggestion
        tracing::debug!(address, "sending gas to client");
```

File: crates/walrus-service/src/client/refill.rs [hunk 3]
```diff
@@ -131,7 +131,7 @@ impl WalletCoinRefill {
     }
 
     async fn send_wal(&self, address: SuiAddress) -> Result<()> {
-        tracing::debug!("Sending wal to address: {:?}", &address);
+        tracing::debug!("sending WAL to {address}");
```
Comment (giac-mysten) [inline crates/walrus-service/src/client/refill.rs]: Nit:
```suggestion
        tracing::debug!(address, "sending WAL to client");
```

File: crates/walrus-service/src/node.rs [hunk 4]
```diff
@@ -592,7 +592,7 @@ impl StorageNode {
                         && event.event_epoch() + 1 < epoch_at_start
                     {
                         tracing::warn!(
-                            "the current epoch ({}) is far ahead of the event epoch: {};
+                            "the current epoch ({}) is far ahead of the event epoch ({}); \
                             node entering recovery mode",
                             epoch_at_start,
                             event.event_epoch()
```
Comment (giac-mysten) [inline crates/walrus-service/src/node.rs:607]:
```suggestion
                            current_epoch = epoch_at_start,
                            event_epoch = event.event_epoch()
                            "the current epoch is far ahead of the event epoch; \
                            node entering recovery mode",

```

File: crates/walrus-service/src/client/cli/runner.rs (hunk 1 above)
Comment (mlegner) [reply crates/walrus-service/src/client/cli/runner.rs:320]: I think I used/kept string formatting in ~~two~~ three cases:
1. When the logs are mainly intended for end users as in this case. These cases should actually be replaced by the mechanisms added in #1214.
2. When the formatted variables are (somewhat) necessary to create a useful message in the first place.
3. In tests where logs are mainly manually inspected and not filtered through tools.

I could rebase this PR on #1214 and improve the first category. WDYT?

File: crates/walrus-service/src/client/refill.rs (hunk 3 above)
Comment (mlegner) [reply crates/walrus-service/src/client/refill.rs]: Done in 15229c1989a12e7b8e4b84180e0a007b5505fde9.

File: crates/walrus-service/src/client/refill.rs (hunk 2 above)
Comment (mlegner) [reply crates/walrus-service/src/client/refill.rs]: Done in 15229c1989a12e7b8e4b84180e0a007b5505fde9.

File: crates/walrus-service/src/node.rs (hunk 4 above)
Comment (mlegner) [reply crates/walrus-service/src/node.rs:607]: Given this is a one-time log entry at startup, I'd rather leave it as it is now.

File: crates/walrus-service/src/client/cli/runner.rs (hunk 1 above)
Comment (mlegner) [reply crates/walrus-service/src/client/cli/runner.rs:320]: I tried to minimize (2) in 15229c1989a12e7b8e4b84180e0a007b5505fde9. Maybe (1) could be done in #1214 or in a follow-up?

Comment (giac-mysten) [reply crates/walrus-service/src/client/cli/runner.rs:320]: sounds good! thanks for the clarification

Comment (giac-mysten) [reply crates/walrus-service/src/client/cli/runner.rs:320]: ~~I can try to add (1) to #1214~~
tracked in an issue #1231
