### PR TITLE
fix(node): correct status tracking for blob extensions

### LINKED ISSUE #1163: Internal blob tracking does not correctly handle blob extensions
The registration expiration is not correctly updated such that nodes conclude the blob is no longer registered. See #1161 for the resulting issue.

### PR DESCRIPTION
**Pull request by mlegner**
Contains a temporary fix for already existing `blob_info` entries that may be incorrect due to the bug.

The added tests failed before the change and pass with the change.

Closes #1163

### CODE REVIEW

File: crates/walrus-service/src/node/storage/blob_info.rs [hunk 1]
```diff
@@ -865,9 +905,20 @@ impl BlobInfoApi for BlobInfoV1 {
...
         let exists_registered_permanent_blob = permanent_total
             .as_ref()
-            .is_some_and(|p| p.end_epoch > current_epoch);
+            .is_some_and(|p| p.end_epoch > current_epoch)
+
+            // TODO(mlegner): This is a temporary workaround due to a previous bug (#1163) with the
+            // blob-status tracking. This is no longer needed after a full redeployment.
+            || permanent_certified
+                .as_ref()
+                .is_some_and(|p| p.end_epoch > current_epoch);
```
Comment (halfprice) [inline crates/walrus-service/src/node/storage/blob_info.rs:914]: I suspect that this is needed unless we run a one shot job to fix all the existing register. I think it's fine to just leave the additional check permanenetly.

Comment (mlegner) [reply crates/walrus-service/src/node/storage/blob_info.rs:914]: Yes, exactly. We can revisit this in a few months and decide if we want to keep it or remove it (will be slightly more performant).
