### PR TITLE
fix(cli): replace deprecated `clap` attributes with `command` or `arg`

### LINKED ISSUE #1944: Deprecated #[clap(...)] attributes causing warnings/errors
### Description

In **clap** version 4.x and above, the use of `#[clap(...)]` is no longer valid.  
Many instances of `#[clap(...)]` are still present in the project.  
These should be replaced with `#[arg(...)]` or `#[command(...)]`.

Error : 

Image

Image

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### PR DESCRIPTION
**Pull request by Himess**
## Description
Fixes #1944 

This PR updates deprecated #[clap(...)] attributes to their modern equivalents in clap 4.x.
The current codebase still uses outdated syntax that has been deprecated since version 4.0.
By making this update, we ensure compatibility with future versions and maintain code quality.

I ran cargo check --features clap/deprecated after making the changes, and the previous clap deprecation warnings are no longer present.

## Test plan
cargo check --features clap/deprecated

Pasted Graphic 6

### CODE REVIEW

File: crates/walrus-stress/src/main.rs [hunk 1]
```diff
@@ -38,35 +38,35 @@ const COIN_REFILL_AMOUNT: u64 = 500_000_000;
 const MIN_BALANCE: u64 = 1_000_000_000;
 
 #[derive(Parser)]
-#[clap(rename_all = "kebab-case")]
-#[clap(name = env!("CARGO_BIN_NAME"))]
+#[command(rename_all = "kebab-case")]
+#[command(name = env!("CARGO_BIN_NAME"))]
```
Comment (mlegner) [inline crates/walrus-stress/src/main.rs]: Nit: If we're already cleaning up:
```suggestion
#[command(name = env!("CARGO_BIN_NAME"), rename_all = "kebab-case")]
```

File: crates/walrus-proxy/src/main.rs [hunk 2]
```diff
@@ -32,11 +32,11 @@ static APP_USER_AGENT: &str = const_str::concat!(
 );
 
 #[derive(Parser, Debug)]
-#[clap(rename_all = "kebab-case")]
-#[clap(name = env!("CARGO_BIN_NAME"))]
-#[clap(version = VERSION)]
+#[command(rename_all = "kebab-case")]
+#[command(name = env!("CARGO_BIN_NAME"))]
+#[command(version = VERSION)]
```
Comment (mlegner) [inline crates/walrus-proxy/src/main.rs]: Nit: If we're already cleaning up:
```suggestion
#[command(
    name = env!("CARGO_BIN_NAME"), 
    version = VERSION),
    rename_all = "kebab-case",
)]
```

File: crates/walrus-orchestrator/src/main.rs [hunk 3]
```diff
@@ -39,7 +39,7 @@ type ClientParameters = ProtocolClientParameters;
 /// The orchestrator command line options.
 #[derive(Parser, Debug)]
 #[command(author, version, about = "Testbed orchestrator", long_about = None)]
-#[clap(rename_all = "kebab-case")]
+#[command(rename_all = "kebab-case")]
```
Comment (mlegner) [inline crates/walrus-orchestrator/src/main.rs]:
```suggestion
#[command(
    author, 
    version, 
    about = "Testbed orchestrator", 
    long_about = None,
    rename_all = "kebab-case"
)]
```

File: crates/walrus-service/bin/backup.rs [hunk 4]
```diff
@@ -21,12 +21,12 @@ use walrus_service::{
 
 /// Manage and run Walrus backup nodes
 #[derive(Parser)]
-#[clap(rename_all = "kebab-case")]
+#[command(rename_all = "kebab-case")]
 #[clap(name = env!("CARGO_BIN_NAME"))]
 #[clap(version = VERSION)]
```
Comment (mlegner) [inline crates/walrus-service/bin/backup.rs]:
```suggestion
#[command(
    name = env!("CARGO_BIN_NAME"),
    version = VERSION,
    rename_all = "kebab-case",
)]
```

File: crates/walrus-service/bin/client.rs [hunk 5]
```diff
@@ -20,12 +20,12 @@ pub const VERSION: &str = walrus_service::utils::version!();
 /// The command-line arguments for the Walrus client.
 #[derive(Parser, Debug, Clone, Deserialize)]
 #[command(author, version, about = "Walrus client", long_about = None)]
-#[clap(name = env!("CARGO_BIN_NAME"))]
-#[clap(version = VERSION)]
-#[clap(rename_all = "kebab-case")]
+#[command(name = env!("CARGO_BIN_NAME"))]
+#[command(version = VERSION)]
+#[command(rename_all = "kebab-case")]
```
Comment (mlegner) [inline crates/walrus-service/bin/client.rs]: Nit: Can we combine these as well?

File: crates/walrus-service/bin/deploy.rs [hunk 6]
```diff
@@ -30,17 +30,17 @@ use walrus_sui::{
 
 const VERSION: &str = version!();
 #[derive(Parser)]
-#[clap(rename_all = "kebab-case")]
-#[clap(name = env!("CARGO_BIN_NAME"))]
-#[clap(version = VERSION)]
+#[command(rename_all = "kebab-case")]
+#[command(name = env!("CARGO_BIN_NAME"))]
+#[command(version = VERSION)]
```
Comment (mlegner) [inline crates/walrus-service/bin/deploy.rs]: Nit: Can we combine these as well?

**Review by mlegner — COMMENTED** [review]
Thanks a lot for helping to keep our code tidy! 🙏 

Just a few minor additional suggestions.

File: crates/walrus-service/bin/client.rs [hunk 7]
```diff
@@ -19,13 +19,18 @@ pub const VERSION: &str = walrus_service::utils::version!();
 
 /// The command-line arguments for the Walrus client.
 #[derive(Parser, Debug, Clone, Deserialize)]
-#[command(author, version, about = "Walrus client", long_about = None)]
-#[clap(name = env!("CARGO_BIN_NAME"))]
-#[clap(version = VERSION)]
-#[clap(rename_all = "kebab-case")]
+#[command(
+    author,
+    version,
```
Comment (mlegner) [inline crates/walrus-service/bin/client.rs]: I think we have the `version` twice.

```suggestion
```

File: crates/walrus-service/bin/backup.rs [hunk 8]
```diff
@@ -21,12 +21,14 @@ use walrus_service::{
...
+    name = env!("CARGO_BIN_NAME"),
+    version = VERSION,
+    rename_all = "kebab-case",
+)]
 #[derive(Debug)]
 struct Args {
-    #[clap(long, short, help = "Specify the config file path to use")]
+    #[arg(long, short, help = "Specify the config file path to use")]
     config: PathBuf,
     #[clap(
```
Comment (mlegner) [inline crates/walrus-service/bin/backup.rs]: There is another instance of `clap` here:
```suggestion
    #[arg(
```

File: crates/walrus-orchestrator/src/main.rs [hunk 9]
```diff
@@ -38,8 +38,13 @@ type ClientParameters = ProtocolClientParameters;
...
+#[command(
+    author, 
+    version, 
+    about = "Testbed orchestrator", 
+    long_about = None,
+    rename_all = "kebab-case"
+)]
 pub struct Opts {
     /// The path to the settings file. This file contains basic information to deploy testbeds
     /// and run benchmarks such as the url of the git repo, the commit to deploy, etc.
```
Comment (mlegner) [inline crates/walrus-orchestrator/src/main.rs:50]: There is another instance of `clap` here.

File: crates/walrus-orchestrator/src/main.rs [hunk 10]
```diff
@@ -52,70 +57,70 @@ pub struct Opts {
...
         /// The number of clients to deploy.
-        #[clap(long, value_name = "INT", default_value_t = 4, global = true)]
+        #[arg(long, value_name = "INT", default_value_t = 4, global = true)]
         clients: usize,
 
         /// Whether to skip testbed updates before running benchmarks. This is a dangerous
         /// operation as it may lead to running benchmarks on outdated nodes. It is however
         /// useful when debugging in some specific scenarios.
-        #[clap(long, action, default_value_t = false, global = true)]
+        #[arg(long, action, default_value_t = false, global = true)]
```
Comment (mlegner) [inline crates/walrus-orchestrator/src/main.rs]: Nit:
```suggestion
        #[arg(long, global = true)]
```

File: crates/walrus-orchestrator/src/main.rs [hunk 11]
```diff
@@ -52,70 +57,70 @@ pub struct Opts {
...
         skip_testbed_update: bool,
 
         /// Whether to skip testbed configuration before running benchmarks. This is a dangerous
         /// operation as it may lead to running benchmarks on misconfigured nodes. It is however
         /// useful when debugging in some specific scenarios.
-        #[clap(long, action, default_value_t = false, global = true)]
+        #[arg(long, action, default_value_t = false, global = true)]
```
Comment (mlegner) [inline crates/walrus-orchestrator/src/main.rs]: Nit:
```suggestion
        #[arg(long, global = true)]
```

File: crates/walrus-orchestrator/src/main.rs [hunk 12]
```diff
@@ -38,8 +38,13 @@ type ClientParameters = ProtocolClientParameters;
 
 /// The orchestrator command line options.
 #[derive(Parser, Debug)]
-#[command(author, version, about = "Testbed orchestrator", long_about = None)]
-#[clap(rename_all = "kebab-case")]
+#[command(
+    author, 
+    version, 
+    about = "Testbed orchestrator",
```
Comment (mlegner) [inline crates/walrus-orchestrator/src/main.rs]: Nit (trailing whitespace):
```suggestion
    author,
    version,
    about = "Testbed orchestrator",
```

**Review by mlegner — COMMENTED** [review]
Thanks for the changes. A few more nits, then let's get it merged. 🙂

**Comment by Himess** [comment]
@mlegner Hopefully I got it right this time 😄.
