### PR TITLE
fix: clean up all `unwrap`s in production code

### LINKED ISSUE #765: Check all `unwrap`s in the codebase
Something that came up during the incident review. 
There seem to be `unwrap`s in the codebase that are not commented/marked.

Check if this is true, remove them, or turn them to `expect`s.

### PR DESCRIPTION
**Pull request by mlegner**
This PR removes all instances of `unwrap` in production code. This excludes tests, benchmarks, and the `walrus-orchestrator` crate.

Some cases are replaced by an `expect` explaining the reason why this can never panic. In some cases a slight rewrite of the code allowed removing the unwrapping altogether.

There are two cases where the previous behavior was potentially problematic:
- In `crates/walrus-event/src/checkpoint_processor.rs`
- The authorization header in `crates/walrus-service/src/node/server/extract.rs` and `crates/walrus-service/src/node/server/routes.rs`.

Closes #765

### CODE REVIEW

File: crates/walrus-service/src/node/server/extract.rs [hunk 1]
```diff
@@ -126,7 +128,7 @@ where
                     StatusCode::INTERNAL_SERVER_ERROR,
                     StatusCode::INTERNAL_SERVER_ERROR
                         .canonical_reason()
-                        .unwrap(),
+                        .expect("this definitely has a canonical reason"),
```
Comment (giac-mysten) [inline crates/walrus-service/src/node/server/extract.rs:131]: 😂
