### PR TITLE
test: fix the local testbed setup

### LINKED ISSUE #290: Make the local testbed great again
Currently, the local testbed is not functioning due to some issues that were introduced in past refactorings and problems with the Sui connection.

I believe that the main issue is that there is only one coin in the various wallets, but we need two: One for paying and one for gas.

### PR DESCRIPTION
**Pull request by mlegner**
- Call the faucet twice to ensure that two coins are available (one for payment and one for gas).
- Sleep between registering a blob and sending data to storage nodes.
- Fix incorrect commands and instructions in testbed script.
- Fail early in testbed script.

Closes #290

### CODE REVIEW

File: crates/walrus-service/src/testbed.rs [hunk 1]
```diff
@@ -111,10 +111,16 @@ pub async fn testbed_configs(
...
+    let mut faucet_requests = Vec::with_capacity(4);
+    for wallet in [&mut admin_wallet, &mut client_wallet] {
+        for _ in 0..2 {
+            faucet_requests.push(request_sui_from_faucet(
+                wallet.active_address()?,
+                sui_network,
+                &sui_client,
+            ))
+        }
+    }
```
Comment (karlwuest) [inline crates/walrus-service/src/testbed.rs:123]:
```suggestion
    let faucet_requests = [
        admin_wallet.active_address()?,
        client_wallet.active_address()?,
    ]
    .into_iter()
    .flat_map(|address| {
        (0..2).map(move |_| request_sui_from_faucet(address, sui_network, sui_client))
    });
```
Not much shorter, but I liked it 🙂 Feel free to ignore.

File: crates/walrus-service/src/client.rs [hunk 2]
```diff
@@ -98,6 +98,10 @@ impl<T: ContractClient> Client<T> {
                 metadata.metadata().encoding_type,
             )
             .await?;
+
+        // We need to wait to be sure that the storage nodes received the registration event.
+        sleep(Duration::from_secs(1)).await;
```
Comment (karlwuest) [inline crates/walrus-service/src/client.rs:103]: Remark: Instead of sleeping here for an arbitrary amount of time, we could also wait until we receive the associated event. This would require a function to get events in reverse order to get the newest, so I don't think this should be part of this PR, but I added #293 to keep track of this.

Comment (mlegner) [reply crates/walrus-service/src/client.rs:103]: Thanks for creating the issue. 👍

File: crates/walrus-service/src/testbed.rs (hunk 1 above)
Comment (mlegner) [reply crates/walrus-service/src/testbed.rs:123]: Unfortunately, that version doesn't compile. I'll just keep my original version. 😁

Comment (karlwuest) [reply crates/walrus-service/src/testbed.rs:123]: >Unfortunately, that version doesn't compile. I'll just keep my original version. 😁

Ahh, I forgot to also mention that the assignment of `sui_client` needs to be changed to 
`let sui_client = &admin_wallet.get_client().await?;`
