### PR TITLE
test: use Mysten failpoints instead of the fail crate for failure injection tests

### LINKED ISSUE #726: Migrate the usage of fail crate to sui internal fail_point
So that we can use the same failpoint implementation for both simtest and failure injection test.

### PR DESCRIPTION
**Pull request by halfprice**
This PR replaces the use of fail/failpoints with Mysten's fail point implementation in place.

The TODO also mentioned to move these tests to walrus-simtest (or walrus-e2e-tests), and it turns out that it is very complicated to do so. These tests are not high level integration tests, and they currently use many crate-only functions. 

Once epoch change is implemented, we can add more high level integration tests in walrus-simtest uses the same failpoints.

close #726

### CODE REVIEW

File: crates/walrus-test-utils/src/lib.rs [hunk 1]
```diff
@@ -166,6 +166,43 @@ macro_rules! async_param_test {
...
+        simtest_param_test!( $func_name -> (): [ $( #[sim_test] $case_name: ($($args),+) ),* ] );
+    };
+    ($func_name:ident -> $return_ty:ty: [
+        $( $case_name:ident: ( $($args:expr),+ ) ),+$(,)?
+    ]) => {
+        simtest_param_test!(
+            $func_name -> $return_ty: [ $( #[sim_test] $case_name: ( $($args),+ ) ),* ]
+        );
+    }
+}
```
Comment (mlegner) [inline crates/walrus-test-utils/src/lib.rs]: AFAICT, the only difference between this and the `async_param_test` is the default `#[sim_test]` instead of `#[tokio::test]` attribute.

Suggestion: 
```suggestion
/// Macro for creating parametrized *simtest* tests.
///
/// This is identical to the [`async_param_test`], except that it annotates the tests with
/// `#[sim_test]` instead of `#[tokio::test]`.
#[macro_export]
macro_rules! simtest_param_test {
    ($func_name:ident: [
        $( $case_name:ident: ( $($args:expr),+ ) ),+$(,)?
    ]) => {
        $crate::async_param_test!(
            $func_name -> (): [ $( #[sim_test] $case_name: ($($args),+) ),* ]
        );
    };
    ($func_name:ident -> $return_ty:ty: [
        $( $case_name:ident: ( $($args:expr),+ ) ),+$(,)?
    ]) => {
        $crate::async_param_test!(
            $func_name -> $return_ty: [ $( #[sim_test] $case_name: ( $($args),+ ) ),* ]
        );
    }
}
```

File: crates/walrus-service/src/node.rs
Comment (mlegner) [inline crates/walrus-service/src/node.rs:1]: Important: We currently run simtests with the command `cargo simtest --run-ignored all simtest`, see [here](https://github.com/MystenLabs/walrus/blob/78b2c7b8b8432b9e351ece60f5142447993d962a/.github/workflows/code.yml#L162) and [here](https://github.com/MystenLabs/walrus/blob/78b2c7b8b8432b9e351ece60f5142447993d962a/CONTRIBUTING.md#simtests).

This only includes tests that have "simtest" somewhere in the name. So we either need to change that or make sure that all simtests are named according to that scheme.

File: crates/walrus-service/src/node.rs [hunk 2]
```diff
@@ -2457,8 +2460,8 @@ mod tests {
         // Note that currently, each sync batch contains 10 blobs. So testing various interesting
         // places to break the sync process.
         // TODO(#705): make shard sync parameters configurable.
-        async_param_test! {
-            sync_shard_start_from_progress -> TestResult: [
+        simtest_param_test! {
+            sync_shard_start_from_progress: [
```
Comment (mlegner) [inline crates/walrus-service/src/node.rs]: Question: What is the reason to remove the return value? This seems to cause quite a lot of additional "expect"s in the code.

File: crates/walrus-test-utils/src/lib.rs (hunk 1 above)
Comment (halfprice) [reply crates/walrus-test-utils/src/lib.rs]: Applied

File: crates/walrus-service/src/node.rs
Comment (halfprice) [reply crates/walrus-service/src/node.rs:1]: Thanks for the info! I added `simtest` to the test names affected in this PR, but I suspect that this may get overlooked again.

I think `cargo simtest --run-ignored all` is probably just fine?

File: crates/walrus-service/src/node.rs (hunk 2 above)
Comment (halfprice) [reply crates/walrus-service/src/node.rs]: What I encountered originall was that, simtest requires function output to be a `send` (https://github.com/MystenLabs/mysten-sim/blob/b320996d8dfb99b273fe31c0222c659332283c99/msim/src/sim/runtime/mod.rs#L461). I tried to make `TestResult` a `send`, but it still has error that `ProtocolKeyPair::from_str` is not send.

It turns out that all I need to do is to add `send` to KeyPairParseError (see the change in `crates/walrus-core/src/keys.rs`). How simtest can also return TestResult.

File: crates/walrus-service/src/node.rs
Comment (mlegner) [reply crates/walrus-service/src/node.rs:1]: Unfortunately without the filter I get errors like "not implemented: this test can only be run in tokio" for many test cases... 🤷

Comment (halfprice) [reply crates/walrus-service/src/node.rs:1]: I see. Yeah, simtest automatically adds a `ignore` to non-sim async test. But by running with `--run-ignored all`, we re-enable them... That's why I tried `cargo simtest`, and it was just fine.

Comment (halfprice) [reply crates/walrus-service/src/node.rs:1]: created https://github.com/MystenLabs/walrus/pull/823
