### PR TITLE
fix: check latest committee epoch before sync

### LINKED ISSUE #877: Shard that is catching up after DB wipe retries to perform epoch change and fails
When wiping (or losing) the DB of a storage node and restarting it, it tries to catch up and recover its data.

During that process, it also retries to perform epoch changes and fails doing that:

```
Sep 27 10:02:03 vultr walrus-node[622833]: 2024-09-27T10:02:03.726953Z  INFO walrus_sui::client: calling epoch_sync_done Some(0xc27b1dcaacf47d7e0b92e33f6f4b913d7f2d3cd4da3cecff9c9d754be123519e)
Sep 27 10:02:05 vultr walrus-node[622833]: 2024-09-27T10:02:05.619770Z ERROR move_call_and_transfer{function=FunctionTag { name: "epoch_sync_done", module: "staking", type_params: [], n_object_outputs: 0 } call_args=[Object(SharedObject { id: 0x51fd824b2e5c9b58aedfe66867a5d92ffe41a1bb0b20c38b6bd42201432d4225, initial_shared_version: SequenceNumber(162191759), mutable: true }), Object(ImmOrOwnedObject((0xc27b1dcaacf47d7e0b92e33f6f4b913d7f2d3cd4da3cecff9c9d754be123519e, SequenceNumber(162219592), o#5Woaep25c6p9FZGPcjLBuGiLRQvBkg9FokGk9GvBfv2G))), Object(SharedObject { id: 0x0000000000000000000000000000000000000000000000000000000000000006, initial_shared_version: SequenceNumber(1), mutable: false })]}: walrus_sui::client: error=transaction execution failed: MoveAbort(MoveLocation { module: ModuleId { address: 2f6952fd3e61970168b5756e1a34a8f458ffc62290527b97c5d79e2aa4ec975d, name: Identifier("staking_inner") }, function: 26, instruction: 16, function_name: Some("epoch_sync_done") }, 9223374562295873542) in command 0
Sep 27 10:02:05 vultr walrus-node[622833]: 2024-09-27T10:02:05.619823Z ERROR walrus_service::node::contract_service: submitting epoch sync done to contract failed error=TransactionExecutionError("MoveAbort(MoveLocation { module: ModuleId { address: 2f6952fd3e61970168b5756e1a34a8f458ffc62290527b97c5d79e2aa4ec975d, name: Identifier(\"staking_inner\") }, function: 26, instruction: 16, function_name: Some(\"epoch_sync_done\") }, 9223374562295873542) in command 0")
```

### PR DESCRIPTION
**Pull request by jpcsmith**
Closes #877

### CODE REVIEW

File: crates/walrus-sui/src/client.rs [hunk 1]
```diff
@@ -764,19 +768,23 @@ impl ContractClient for SuiContractClient {
...
+        .ok_or(SuiClientError::StorageNodeCapabilityObjectNotSet)?;
 
-        tracing::info!("calling epoch_sync_done {:?}", node_capability_object_id);
-        if node_capability_object_id.is_none() {
-            return Err(SuiClientError::StorageNodeCapabilityObjectNotSet);
+        let node_capability: StorageNodeCap =
+            get_sui_object(&self.read_client.sui_client, node_capability_object_id).await?;
+        if node_capability.last_epoch_sync_done >= epoch {
+            return Err(SuiClientError::LatestAttestedIsMoreRecent);
         }
```
Comment (jpcsmith) [inline crates/walrus-sui/src/client.rs]: @karlwuest Is this check sufficient? I assume that there would be gaps since a given node may not attest to every epoch, but this ensures that he does not attest to epochs in the past.

Comment (karlwuest) [reply crates/walrus-sui/src/client.rs]: Yes, that check is sufficient.

File: crates/walrus-sui/src/client.rs [hunk 2]
```diff
@@ -764,19 +768,23 @@ impl ContractClient for SuiContractClient {
         .await?
         .collect::<Vec<_>>()
         .iter()
-        .find_map(|cap| (cap.node_id == node_id).then_some(cap.id));
+        .find_map(|cap| (cap.node_id == node_id).then_some(cap.id))
```
Comment (karlwuest) [inline crates/walrus-sui/src/client.rs]: Suggestion: Don't map to the ID here, then you get the cap already and don't need to re-fetch it below.

File: crates/walrus-sui/src/client.rs [hunk 3]
```diff
@@ -764,19 +768,23 @@ impl ContractClient for SuiContractClient {
...
+        .ok_or(SuiClientError::StorageNodeCapabilityObjectNotSet)?;
 
-        tracing::info!("calling epoch_sync_done {:?}", node_capability_object_id);
-        if node_capability_object_id.is_none() {
-            return Err(SuiClientError::StorageNodeCapabilityObjectNotSet);
+        let node_capability: StorageNodeCap =
+            get_sui_object(&self.read_client.sui_client, node_capability_object_id).await?;
```
Comment (karlwuest) [inline crates/walrus-sui/src/client.rs]: See above, this can be removed.

File: crates/walrus-sui/src/client.rs (hunk 2 above)
Comment (jpcsmith) [reply crates/walrus-sui/src/client.rs]: Thank you for catching this.

File: crates/walrus-sui/src/client.rs [hunk 4]
```diff
@@ -754,29 +758,29 @@ impl ContractClient for SuiContractClient {
...
+            return Err(SuiClientError::LatestAttestedIsMoreRecent);
         }
 
+        tracing::debug!("calling epoch_sync_done {:?}", node_capability.node_id);
         let cap_obj_ref = self
             .wallet
             .lock()
             .await
-            .get_object_ref(node_capability_object_id.expect("We just checked it is not none"))
+            .get_object_ref(node_capability.node_id)
```
Comment (mlegner) [inline crates/walrus-sui/src/client.rs]: Important:
```suggestion
            .get_object_ref(node_capability.id)
```
